language: python
cache: pip
python:
    - "3.8"
    - "3.9"
    - "3.10"
    # May have a problem due to 'longintrepr.h'
    - "3.11"

install:
    - sudo apt-get update
    # https://github.com/scikit-sparse/scikit-sparse#installation
    - sudo apt-get install libsuitesparse-dev
    # package reqs
    - pip install --upgrade pip
    # test reqs
    - pip install -r requirements.txt
    - pip install scikit-sparse
    # brings in all the mandatory deps
    - pip install .

script:
    - pytest --cov=pygam

after_success:
    - codecov
