[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "pygam"
author = "Daniel Serven"
author-email = "dswahpypi@gmail.com"
home-page = "https://github.com/dswah/pyGAM"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
requires = [
    "numpy<1.24.0",
    "progressbar2",
    "scipy",
]
requires-python = ">=3.8"
keywords = "machine-learning data-science scientific-computing"

